const one = "hi";
const two = "hello";
const wee = `${one}${two}`;
console.log(wee);
const greeting = "Hello";
const name = "Chris";
console.log(greeting + ", " + name);
const myText = 'I am a string';
const newString = myText.replace('string', 'sausage');
console.log(newString);